spring.data.mongodb.uri=mongodb+srv://JAIROTR1:1086222353jV#@cluster0.ptleaih.mongodb.net/bibliotecadb?retryWrites=true&w=majority&appName=Cluster0
spring.application.name=biblioteca-app
server.port=8080
spring.mvc.pathmatch.use-suffix-pattern=false
